### ISSUE TITLE
Overview of transactions/usecases

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/ch-atc#12]
Perhaps it would be usefull to have a deeper description of the use case with the transactions next to the link to the IHE profile.

**Comment by oliveregger** [comment]
Profile, transaction are currently specified in the annex and not included in the IG, tbd:
https://ehealthsuisse.ihe-europe.net/docs/reference_documents/3.2/EPDV-EDI_Anhang_5_E2.2_DE_Ausgabe_1_ATC.pdf

**Comment by oliveregger** [comment]
Teco MS/DK/OE: We will integrate volume 1, 2, 3 from A5E2.2 into the FHIR Implementation Guide. This will allow in a future version to simplify A5E2.2. (e.g. remove examples etc).
