### ISSUE TITLE
Support for Tracecontext

### ISSUE THREAD

**Issue by oliveregger** [ehealthsuisse/ch-atc#18]
The tracecontext should be added in the profile that the information can be correlated:
- [DocumentAuditEventType](https://fhir.ch/ig/ch-atc/ValueSet-DocumentAuditEventType.html)
- [PolicyAuditEventType](https://fhir.ch/ig/ch-atc/ValueSet-PolicyAuditEventType.html)
- [AccessAuditTrailEventType](https://fhir.ch/ig/ch-atc/ValueSet-AccessAuditTrailEventType.html)

This will allow afterwards the portal to correlate/group the AuditEvents with the same traceparent.

**Comment by oliveregger** [comment]
see also https://github.com/ehealthsuisse/ch-epr-mhealth/issues/153

**Comment by ziegm** [comment]
page for it is created as preparation: https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/tracecontext.html

**Comment by ziegm** [comment]
@oliveregger please review the changes:
- Profiles:
   - https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/StructureDefinition-HpdAuditEvent.html
   - https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/StructureDefinition-PolicyAuditEvent.html
   - https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/StructureDefinition-DocumentAuditEvent.html
   - https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/StructureDefinition-AccessAuditTrailEvent.html
- Examples: https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/artifacts.html#example-example-instances
- Changelog: https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/changelog.html
