### ISSUE TITLE
New validation error (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [ehealthsuisse/ch-atc#21]
With newer versions of the IG publisher this error occured

Bundle​.entry[3]​.resource​.issue[0]​.details (l341​/c30)
The extension http://hl7.org/fhir/StructureDefinition/artifact-identifier is not allowed to be used at this point (allowed = e:Resource; this element is [Bundle.entry.resource.issue.details, CodeableConcept, OperationOutcome.issue.details])

**Comment by oliveregger** [comment]
The extension has changed the context, it is not allowed anymore on the OperationOutcome.detail:

https://hl7.org/fhir/extensions/StructureDefinition-artifact-identifier.profile.json.html

**Comment by oliveregger** [comment]
We don't have an extension within HL7/IHE and it looks not that we can easily integrate it in [MHD](https://github.com/IHE/ITI.BasicAudit/pull/77), i propose that we add the extension to CH EPR FHIR and depend with CH-ATC on it.

**Comment by ziegm** [comment]
@oliveregger could you please review the change:
https://github.com/ehealthsuisse/ch-atc/commit/07959c339588634254184b70f17e66d9e9351a08
