### ISSUE TITLE
Textuel improvement of narrative part in example of "Creation of a Document"

### ISSUE THREAD

**Issue by dkotlaris** [ehealthsuisse/ch-atc#24]
Narrative part in the example:

"Upload of Record Artifact 10.10.2020 18:29 from Julia Helfe-Gern on behalf of Jakob Wieder-Gesund"

Should the document title be: «Austrittsbericht von Julia Helfe-Gern» instead of "Record Artifact"?

https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/AuditEvent-atc-doc-create-rep-pat.xml.html

**Comment by ziegm** [comment]
@dkotlaris @oliveregger 
Record artifact is also used here:
- https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/AuditEvent-atc-doc-create-rep-pat.xml.html (as mentioned above)
   - https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/Bundle-ch-atc-iti-81-response-sample.xml.html
- Table 6: Uploading a Record Artifact by a patient representative (atc-doc-create-rep-pat) 
- https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/AuditEvent-atc-doc-read-ass-hpc.xml.html (Regula Fischer)

Record artifact is coming from:
Resource: type of Document	Nicht näher bezeichnetes Dokument (SNOMED CT: 419891008)
not 
Resource title of Document	Austrittsbericht von Julia Helfe-Gern

Should we really change it?

**Comment by oliveregger** [comment]
we don't have document title in the structured audit event, therefore i would not put it into the narrative

**Comment by dkotlaris** [comment]
Both, the title and the type of the document are contained in the Document Audit Event.
Since this is only the narrative part, we can also leaf it with the type 'Record Artifact'.
