### ISSUE TITLE
Textual improvement: 4.3 Policy Audit Event Content Profile

### ISSUE THREAD

**Issue by dkotlaris** [ehealthsuisse/ch-atc#25]
4.3 Policy Audit Event Content Profile

In Table 8 under Event Type it is stated: “Assign a Healthcare Professional to Blacklist” and “Exclude a Healthcare Professional from Blacklist”

Better: “Exclude a Healthcare Professional from accessing the EPR” and “Revoke the exclusion of a Healthcare Professional from accessing the EPR”

https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/volume-3.html#document-audit-event-content-profile

**Comment by ziegm** [comment]
@dkotlaris you can review the change:
https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/volume-3.html#policy-audit-event-content-profile

**Comment by dkotlaris** [comment]
Looks good. Thanks!
