### ISSUE TITLE
Textuel improvement of narrative part in example of "Create Access Right for Healthcare professional"

### ISSUE THREAD

**Issue by dkotlaris** [ehealthsuisse/ch-atc#26]
CH ATC - Create Access Right for Healthcare professional

"22.09.2020 09:47: Jakob Wieder-Gesund created Access Level delegation-and-restricted till 31.12.2020 08:00 to Dr. med. Hans Allzeitbereit"

Change "created" to "assigned"

https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/AuditEvent-atc-pol-create-acc-right.xml.html

**Comment by ziegm** [comment]
@dkotlaris you can review the changes: 
* https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/AuditEvent-atc-pol-create-acc-right.xml.html
* https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/Bundle-ch-atc-iti-81-response-sample.xml.html

**Comment by dkotlaris** [comment]
Looks good. Thanks!
