### ISSUE TITLE
Typo in Table 11 "EPR-SPID" instead of "EPR_SPID"

### ISSUE THREAD

**Issue by dkotlaris** [ehealthsuisse/ch-atc#27]
4.2 Document Audit Event Content Profile

Typo: "EPR-SPID" instead of "EPR_SPID"

https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/volume-3.html#document-audit-event-content-profile

**Comment by ziegm** [comment]
@dkotlaris you can review the change:
* https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/volume-3.html#access-audit-trail-content-profile

**Comment by dkotlaris** [comment]
Looks good. Thanks!
