### ISSUE TITLE
Textual improvement in narrative part of example "Access of Audit Trail Repository"

### ISSUE THREAD

**Issue by dkotlaris** [ehealthsuisse/ch-atc#28]
In the narrative part it states:
"Jakob Wieder-Gesund has viewed the audit trail 22.09.2020 10:47"

In the body part the display value is: "Accessing the Patient Audit Record Repository"

Change: "has viewed" to "accessed"

https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/AuditEvent-atc-log-read.xml.html

**Comment by ziegm** [comment]
@dkotlaris you can review the changes:
* https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/AuditEvent-atc-log-read.xml.html
* https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/integrationA5E2.2/Bundle-ch-atc-iti-81-response-sample.xml.html

**Comment by dkotlaris** [comment]
Looks good. Thanks!
