### ISSUE TITLE
Typo: The Trace Context is missing in Mapping Table AccessAuditTrailEvent 

### ISSUE THREAD

**Issue by dkotlaris** [ehealthsuisse/ch-atc#35]
In the mapping table AccessAuditTrailEvent https://fhir.ch/ig/ch-atc/StructureDefinition-AccessAuditTrailEvent-mappings.html#mappings-for-ch-atc-https-www-bag-admin-ch-bag-en-home-html the Trace Context has not been added like in the other mapping tables.

**Comment by dkotlaris** [comment]
AG Steuerung Weiterentwicklung rejected the extension of the W3C Trace Context in the EPR on October 24, 2024.
That means, the elaborated solution for the ordinance and the ATC and EPR FHIR IG cannot be integrated in release 2025.

The already made changes in the implementation guide have to be reverted.

**Comment by oliveregger** [comment]
applies to ATC (and not EPR FHIR) as discussed today.

**Comment by dkotlaris** [comment]
No change needed. The AuditEvents in CH ATC reference the [ch-epr-fhir-auditevent](http://fhir.ch/ig/ch-epr-fhir/4.0.1-ballot/StructureDefinition-ch-epr-fhir-auditevent.html) from the CH EPR FHIR IG, where the W3C Trace Context is foreseen but not mandatory. This OK for the CH ATC as well.
