### ISSUE TITLE
Constrain the identifier of the Initiator in the AuditEvents

### ISSUE THREAD

**Issue by dkotlaris** [ehealthsuisse/ch-atc#36]
The agent.who.identifier in the Key Elements Table should be constrained according to the [specifications](https://fhir.ch/ig/ch-atc/volume-3.html#audit-trail-consumption-event-types).

**Comment by dkotlaris** [comment]
Telco 19.11.
Oliver has a look. Check Differential Table or introduce must support.

**Comment by pjolo** [comment]
Done with PR #52
