### ISSUE TITLE
Volume 1 - Integration Profiles (Roeland Luykx, RALY GmbH)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-atc#37]
ch.fhir.ig.ch-atc#3.3.0-ballot /volume-1.html

Does it make sense to write (TODO leere section with link to https://profiles.ihe.net/ITI/TF/Volume1/ch-9.html#9.2.3)? 

Roeland Luykx, RALY GmbH

**Comment by oliveregger** [comment]
https://fhir.ch/ig/ch-atc/3.3.0-ballot/volume-1.html#patient-audit-record-repository

**Comment by dkotlaris** [comment]
Corrected with https://github.com/ehealthsuisse/ch-atc/commit/b402097270dec7e71967c15c4aed3069e8e4d02f.
