### ISSUE TITLE
ITI-81: invalid example of Bearer token

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-atc#39]
The exemple in [Volume 2 - Transactions](https://fhir.ch/ig/ch-atc/volume-2.html#constraints-on-retrieve-atna-audit-event-iti-81) is invalid:
```http
GET /example/url/to/resource/location HTTP/1.1
Authorization: "Bearer" fFBGRNJru1FQd[…omitted for brevity…]44AzqT3Zg
Host: examplehost.com
```

The "Bearer" keyword shall not be wrapped in quotes:

```http
GET /example/url/to/resource/location HTTP/1.1
Authorization: Bearer fFBGRNJru1FQd[…omitted for brevity…]44AzqT3Zg
Host: examplehost.com
```

**Comment by dkotlaris** [comment]
Telco 19.11.
Correct as proposed above. See also https://datatracker.ietf.org/doc/html/rfc6750#section-2.1.

**Comment by pjolo** [comment]
@oliveregger: Review the change
Pull Request: [PR](https://github.com/ehealthsuisse/ch-atc/pull/56)
[Section](https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/39iti_81_invalidexampleofbearertoken/volume-2.html#security-considerations)
[Changelog](https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/39iti_81_invalidexampleofbearertoken/changelog.html)
