### ISSUE TITLE
ITI-81: the 'user' search parameter does not exist

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-atc#40]
In [Volume 2 - Transactions §3.1.2](https://fhir.ch/ig/ch-atc/volume-2.html#additional-atna-search-parameters):

> The Patient Audit Consumer shall not use the following parameters in a query parameters: address, patient.identifier, source, type, user, outcome

The 'user' search parameter does not exist, neither in FHIR, nor in ITI-81.

Also, why these restrictions? Querying on outcome, source or type can be useful to the patient.

**Comment by dkotlaris** [comment]
Telco 19.11.
Remove 'user' from text above (non breaking change).
User was used in FHIR STU3 search parameter https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_Suppl_RESTful-ATNA_Rev2.2_TI_2017-07-21.pdf, but is not in R4 anymore.

**Comment by pjolo** [comment]
@oliveregger : Please review the change:
Pull Request: [PR](https://github.com/ehealthsuisse/ch-atc/pull/55)
Section: [Additional ATNA Search Parameters](https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/40_iti_81_theusersearchparameterdoesnotexist/volume-2.html#constraints-on-retrieve-atna-audit-event-iti-81)
[changelog](https://build.fhir.org/ig/ehealthsuisse/ch-atc/branches/40_iti_81_theusersearchparameterdoesnotexist/changelog.html)
