### ISSUE TITLE
Profiles: why using base64 for AuditEvent.entity.detail.value

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-atc#41]
In multiple profiles (e.g. [DocumentAuditEvent](https://fhir.ch/ig/ch-atc/StructureDefinition-DocumentAuditEvent.html)), the type of `AuditEvent.entity.detail.value` has been fixed to base64Binary, despite the value being a string, not a binary blob.

The FHIR spec says:

> The value can be string when known to be a string, else base64 encoding should be used to protect binary or undefined content.

When storing OIDs, UUIDs, format codes and titles, we are sure they are strings, nothing else. It hurts the readability of the resource for no gain.
The reason is probably the DICOM way of using base64 values in `ParticipantObjectDetail`.

**Comment by oliveregger** [comment]
Most probably it came from https://hl7.org/fhir/STU3/auditevent.html where only base64 was allowed.

**Comment by dkotlaris** [comment]
Yes, with R4 also string is allowed: https://www.hl7.org/fhir/R4/auditevent-definitions.html. To be discussed.

**Comment by dkotlaris** [comment]
Telco 19.11.
It is implemented with base64 and should not be changed. Otherwise the systems would have to be adapted.
CH ATC is still compliant with the AuditEvent specification in FHIR R4.
