### ISSUE TITLE
Volume 3: wrong display name of document type in example

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-atc#43]
In [Volume 3 §4.1.2](https://build.fhir.org/ig/ehealthsuisse/ch-atc/volume-3.html#example-of-a-document-audit-event-document-upload), the display name of the SNOMED CT code 419891008 is not _Nicht näher bezeichnetes Dokument_, but _Sonstige Dokumentation_.

**Comment by dkotlaris** [comment]
Corrected according to https://github.com/ehealthsuisse/ch-atc/commit/295a6911aba709e7a501b5d91bc3715c7f3c0f9f. Thanks for reporting!
