### ISSUE TITLE
Volume 3: typo in footnote

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-atc#44]
In [Volume 3 §4.3](https://build.fhir.org/ig/ehealthsuisse/ch-atc/volume-3.html#policy-audit-event-content-profile), it's written:

> AccessLimitedToDate8

instead of 

>AccessLimitedToDate [8.2]

with 8.2 being a link to the referenced footnote.

**Comment by dkotlaris** [comment]
Typo corrected.
