### ISSUE TITLE
Volume 3: about the UAP-ID use

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-atc#45]
In the [Volume 3](https://build.fhir.org/ig/ehealthsuisse/ch-atc/volume-3.html), the UAP-ID is used multiple times to identify the representative or administrators.
This seems to be a poor choice:

- The UAP-ID is an identifier bound to the IdP account, not the EPR account, meaning an administrator or representative may have multiple UAP-IDs if they have linked multiple IdPs.
- The UAP-ID can change.
- Representatives and administrators have a unique ID managed by the community (as required by the XUA profile), which would be much more suited here.

**Comment by dkotlaris** [comment]
This is a good point. In the ordinance, the "UAP-ID" is only used in the context of the CH ATC profile.
It makes sense not to use the User Authentication Provider (UAP) ID for representatives and other user roles. This should be left to the communities.

The specifications for XUA in Amendment 1 of Annex 5 EPRO-FDHA leave open which identifier can be used for representatives (representative-id), technical users (technical-user-id), document administrators (document-administrator-id) and policy administrators (policy-administrator-id) - in the context of XUA, as you write.

Discuss whether the CH ATC profile should be modified accordingly. But we are already late for Release 2025.

**Comment by dkotlaris** [comment]
Telco 19.11.
Change of UAP-ID to representative-id would be a breaking change. We don't make a change in the IG.
