### ISSUE TITLE
Volume 3: about the use of the EPR-SPID for representatives

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-atc#46]
In the [Volume 3](https://build.fhir.org/ig/ehealthsuisse/ch-atc/volume-3.html), the EPR-SPID can be used to identify a representative. This can be a data privacy issue, because it reveals the representative EPR-SPID (and the fact that they have also opened an EPR) to the patient.

**Comment by dkotlaris** [comment]
I agree. I don't know what IDs the reference communities are using for representatives today.
So I recommend discussing this issue in AG TSI. Maybe we can also solve it with https://github.com/ehealthsuisse/ch-atc/issues/45.

**Comment by dkotlaris** [comment]
Telco 19.11.
Changing the IG to only allow UAP-ID would be a breaking change. We should not change the IG for the moment.
