### ISSUE TITLE
ChAtcIti81Response: align the cardinalities

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-atc#48]
![fhir ch_ig_ch-atc_StructureDefinition-CH-ATC ITI-81 Response html](https://github.com/user-attachments/assets/e7a893ff-00ea-4377-aede-4a5e52334051)

**Comment by dkotlaris** [comment]
Telco 19.11.
Yes, please harmonize the cardinalities. Minimal cardinality should be set to 1.

**Comment by pjolo** [comment]
Done with PR #54
