### ISSUE TITLE
Remove Trace Context from CH ATC Profile

### ISSUE THREAD

**Issue by dkotlaris** [ehealthsuisse/ch-atc#51]
The AG Steuerung Weiterentwicklung decided on October 24, 2024 not to integrate the W3C Trace Context in Release 2025.
Therefore, all changes according to [EHSEPDBEP-222](https://jira.edi.admin.ch/browse/EHSEPDBEP-222) have to be changed back in the CH ATC Profile.

**Comment by pjolo** [comment]
@oliveregger Review the change:

[Pull request](https://github.com/ehealthsuisse/ch-atc/pull/57)
