### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-atc#7]
For all AuditEvent profiles:
Can we get better description of entities? _Patient_, _Healthcare professional_, _Group_, _Document_ are not really descriptive :)
E.g. The patient who is being notified, The HCP that has been added to a group, The group in which a HCP has been added.

In http://fhir.ch/ig/ch-atc/ValueSet-PolicyAuditEventType.html:
ATC_POL_INCL_BLACKLIST has the description "Assign a Healthcare Professional to Blacklist", I would use "Include" for consistency with the chosen code and ATC_POL_EXL_BLACKLIST.

In [atc-doc-create-rep-pat](http://fhir.ch/ig/ch-atc/AuditEvent-atc-doc-create-rep-pat.xml.html):
```xml
<!--  Document  -->
<what>
  <identifier>
    <type>
      <coding>
        <system value="urn:uuid:2e82c1f6-a085-4c72-9da3-8640a32e42ab"/>
        <code value="IHE XDS Metadata"/>
        <display value="XDSDocumentEntry.uniqueId"/>
      </coding>
    </type>
    <system value="urn:ietf:rfc:3986"/>
    <value value="urn:oid:1.2.3.4.5"/>
  </identifier>
</what>
```
`urn:uuid:2e82c1f6-a085-4c72-9da3-8640a32e42ab` is not a system, but could be a code.
`IHE XDS Metadata` is not a code.
`urn:uuid:7edca82f-054d-47f2-a032-9b2a5b5186c1` as a system maybe? https://gazelle.ihe.net/XDStarClient/rimihe-templates/rimihe-XDSDocumentEntry.html

`source.observer.identfiier`: Why not use `source.site`, as mapped by FHIR/IHE?
Annex 5, 2.2 §4.2.1 has errors in this example: the OID is displayed in `source.identifier`, which does not exist.

In [atc-doc-read-ass-hpc](http://fhir.ch/ig/ch-atc/AuditEvent-atc-doc-read-ass-hpc.xml.html):
```xml
<!--  Document  -->
<role>
  <system value="http://terminology.hl7.org/CodeSystem/object-role"/>
  <code value="3"/>
  <display value="Report"/>
</role>
```
**Report** is badly suited here, because the document is not _any kind of persistent document created as a result of the event_, it is only being read. **Domain Resource**?

In [atc-pol-create-acc-right](http://fhir.ch/ig/ch-atc/AuditEvent-atc-pol-create-acc-right.xml.html):
HCPs are **System Objects**, not **Persons** any more? :)
Same for [atc-pol-create-rep](http://fhir.ch/ig/ch-atc/AuditEvent-atc-pol-create-rep.xml.html)

In HpdAuditEvent: I would argue that the patient here has the role of Subscriber, not Patient, because they have no direct relation to the event, but that would be nitpicking.

**Comment by oliveregger** [comment]
1. For all AuditEvent profiles Can we get better description of entities?
tbd: can we describe general for the group more specific?

3.  concerning the textual changes (ATC_POL_INCL_BLACKLIST) in the ValueSet they were provided by the FOPH (including translations), they should provide feedback if we can do chagnes

4. XDSDocumentEntry.uniqueId

```xml
<ns4:ExternalIdentifier id="urn:uuid:df9df3fc-4da7-4603-a8fe-c361676f579d" identificationScheme="urn:uuid:2e82c1f6-a085-4c72-9da3-8640a32e42ab" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:ExternalIdentifier" registryObject="urn:uuid:a3767774-f91b-4d2c-9a17-ce8a2c96e6e2" value="1.3.6.1.4.1.12559.11.1.2.2.1.1.3.479">
		        <ns4:Name>
		            <ns4:LocalizedString value="XDSDocumentEntry.uniqueId"/>
		        </ns4:Name>
		    </ns4:ExternalIdentifier>
```

maybe we could just add?

```xml
      <coding>
        <system value="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:ExternalIdentifier"/>
        <code value="XDSDocumentEntry.uniqueId"/>
      </coding>
```

5. the OID is displayed in source.identifier is incorrect
-> fix with a proper test id

other structural changes proposition: the profiled AuditEvents are in production, I don't think they should be changed, even if there would be structural problems within them. tbd.

**Comment by oliveregger** [comment]
Telco DK/MS: will change the ExternalIdentifier but not make changes to structural message as it is already used in that way.
