### ISSUE TITLE
History page (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [ehealthsuisse/ch-atc#9]
Layout is not the same as for all other Swiss IGs (and not really nice ;-))

**Comment by oliveregger** [comment]
https://github.com/HL7/fhir-ig-history-template
and
https://confluence.hl7.org/display/FHIR/HL7+Process+for+Publishing+a+FHIR+IG

header.template: the content in here is added to the html page above . This is for you to include your own css files etc

see also https://github.com/IHE/publications/blob/master/templates/header.template

we need to change the css for:

--navbar-bg-color: #7b1fad; -> this one is defined in project.css, maybe just remove that in header.template
--footer-container-bg-color: #7b1fad;

and include the ehealth-suisse logo

the history page is created during the publication process

should be put to     
.navbar-inverse {
 background-color: #ad1f2f;
}

**Comment by oliveregger** [comment]
added assets/fhir.css and assets/hl7.css to the history template, this should fix the colors

**Comment by oliveregger** [comment]
need to define a specific header template for the logo
